apiVersion: apps/v1
kind: Deployment
metadata:
  name: becky-ui
spec:
  selector:
    matchLabels:
      app: becky-ui
      service: becky-ui
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: becky-ui
        service: becky-ui
        tier: frontend
    spec:
      containers:
        - name: becky-ui
          image: becky-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
